{
 "title": "Observability Chaos Lab - Prometheus & Loki",
 "tags": [
  "observability",
  "lab",
  "chaos"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU uso (%) - Node Exporter",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memoria usada (bytes) - Node Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Memoria usada"
    }
   ]
  },
  {
   "title": "Logs del sistema (Loki)",
   "type": "logs",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"system-logs\"}"
    }
   ]
  }
 ]
}